import { NAVIGATION_HEIGHT, SCREEN_WIDTH, STATUSBAR_HEIGHT } from '@/utils';
import Colors from '@/utils/colors';
import {
  StyleSheet,
} from 'react-native';
export const styles = StyleSheet.create({
  bgView:{
    flex:1,
  },
  navigationView:{
    width:'100%',
    height:NAVIGATION_HEIGHT,
    flexDirection:'row',
    justifyContent:'space-between',
    alignItems:'center',
    marginTop:STATUSBAR_HEIGHT,
    paddingHorizontal:16,
  },
  backButton:{
    width:NAVIGATION_HEIGHT,
    height:NAVIGATION_HEIGHT,
    justifyContent:'center'
  },
  backIcon:{
    width:16,
    height:16
  },
  collectIcon:{
    width:18,
    height:16
  },
  webView:{
    width:SCREEN_WIDTH,
    height:SCREEN_WIDTH
  },
  modalView:{
    alignItems:'center',
    paddingHorizontal:16,
  },
  modalLine:{
    width:320,
    height:70,
    marginTop:-20,
  },
  name:{
    fontSize:16,
    color:Colors.assist,
    fontWeight:'600',
    marginTop:6
  },
  swiperView:{
    alignItems:'center',
    paddingHorizontal:16,
  },
  swiperTopView:{
    width:'100%',
    height:'100%',
    borderRadius:8,
    backgroundColor: "blue",
  },
  sliderView:{
    backgroundColor:'rgba(109,105,250,0.2)',
    borderRadius:10,
    height:20,
    width:36,
    justifyContent:'center',
    alignItems:'center',
    marginTop:12
  },
  sliderTitle:{
    fontSize:10,
    color:Colors.assist,
    textAlign:'center'
  },
  detailView:{
    borderTopLeftRadius:12,
    borderTopRightRadius:12,
    backgroundColor: 'rgba(255, 255, 255, 1)',
    boxShadow: '0 -2 15 2 rgba(51, 51, 51, 0.05)',
    padding:16,
    marginTop:20
  },
  shopView:{
    flexDirection:'row',
    justifyContent:'space-between'
  },
  shopIcon:{
    width:24,
    height:24,
    borderRadius:12,
    backgroundColor:'rgba(109,105,250,0.2)',
    marginRight:8
  },
  shopName:{
    height:24,
    fontSize:16,
    color:Colors.assist
  },
  shopDes:{
    fontSize:10,
    color:Colors.light
  },
  focusdis:{
    height:24,
    width:70,
    borderRadius:12,
    borderWidth:1,
    borderStyle:'solid',
    borderColor:'rgba(51, 51, 51, 0.05)',
    flexDirection:'row',
    justifyContent:'center',
    alignItems:'center',
  },
  focusSel:{
    backgroundColor:'rgba(109,105,250,0.2)',
  },
  shopFocus:{
    fontSize:14,
    color:Colors.light
  },
  shopFocussel:{
    color:Colors.main
  },
  webDetailView:{
    width:'100%',
    height:1000
  },
  downView:{
    flexDirection:'row',
    position:'absolute',
    height:66,
    width:'100%',
    bottom:0,
    zIndex:10,
    alignItems:'center',
    padding:16,
    backgroundColor:Colors.white
  },
  downViewItem:{
    height:44,
    flex:1,
    borderWidth:1,
    borderStyle:'solid',
    borderColor:Colors.main,
    backgroundColor: 'rgba(109, 105, 250, 0.2)',
    borderRadius:4,
    paddingHorizontal:8,
    flexDirection:'row'
  },
  downViewItemSel:{
    backgroundColor:Colors.main
  },
  buttonContrianer:{
    flex:1,
    height:44,
  },
  downViewItemRight:{
    backgroundColor:'transparent',
    marginLeft:8
  },
  downIcon:{
    width:38,
    height:38,
  },
  downTitle:{
    fontSize:16,
    color:Colors.label,
    flex:1,
    textAlign:'center',
    lineHeight:44,
    fontWeight:'600'
  },
  downTitleSel:{
    color:Colors.white
  },
  showBuyView:{
    height:240,
    flex:1,
    position:'absolute',
    bottom:-240,
    left:0,
    right:0,
    zIndex:6,
    backgroundColor:'red'
  },
  bgModal:{
    position:'absolute',
    zIndex:4,
    top:0,
    left:0,
    right:0,
    bottom:0,
    backgroundColor:'rgba(0,0,0,0.5)',
    flex:1,
    width:'100%',
    height:'100%',
  }
});
