import { NAVIGATION_HEIGHT, SCREEN_WIDTH, STATUSBAR_HEIGHT, SCREEN_HEIGHT, BOTTOM_HEIGHT } from '@/utils';
import Colors from '@/utils/colors';
import {
  Platform,
  StyleSheet,
} from 'react-native';
export const styles = StyleSheet.create({
  mainView:{
    flex:1,
    backgroundColor:'#000'
  },
  bgView:{
    position:'absolute',
    zIndex:-1,
    width:SCREEN_WIDTH,
    height:SCREEN_HEIGHT,
    top:0,
    left:0
  },
  navigationView:{
    width:'100%',
    height:NAVIGATION_HEIGHT + STATUSBAR_HEIGHT,
    flexDirection:'row',
    justifyContent:'space-between',
    // top:STATUSBAR_HEIGHT,
    top:0,
    paddingTop:STATUSBAR_HEIGHT,
    paddingHorizontal:16,
    position:'absolute',
    zIndex:100,
    alignItems:'center'
  },
  contentContainerStyle:{
    paddingTop:Platform.OS === 'ios' ? NAVIGATION_HEIGHT : STATUSBAR_HEIGHT + NAVIGATION_HEIGHT,
    paddingHorizontal:16,
  },
  backButton:{
    width:30,
    height:NAVIGATION_HEIGHT,
    justifyContent:'center',
  },
  backIcon:{
    width:16,
    height:16
  },
  accounticon:{
    width:34,
    height:34,
    marginRight:5,
    borderRadius:17,
    overflow:'hidden'
  },
  accountTitle:{
    fontSize:14,
    color:Colors.white,
    width:130
  },
  downView:{
    flexDirection:'row',
    alignItems:'center',
    height:44,
    borderRadius:22,
    overflow:'hidden',
    marginHorizontal:16
  },
  input:{
    flex:1,
    paddingHorizontal:16
  },
  msgView:{
    flexDirection:'row',
    flex:1,
    marginVertical:10
  },
  avatar:{
    width:44,
    height:44,
    borderRadius:22,
    marginRight:10
  },
  itemRight:{
    flex:1,
  },
  name:{
    fontSize:12,
    color:Colors.light
  },
  contentView:{
    backgroundColor:'rgba(109,105,250,0.5)',
    borderRadius:4,
    marginTop:5,
    flex:1
  },
  content:{
    fontSize:16,
    color:Colors.white,
    padding:5
  },
});
