import { SCREEN_HEIGHT, SCREEN_WIDTH, STATUSBAR_HEIGHT, STATUSBAR_SAFE_AREA_HEIGHT } from '@/utils';
import Colors from '@/utils/colors';
import {
    StyleSheet,
} from 'react-native';
export const styles = StyleSheet.create({
    backButton:{
        width:32,
        height:32,
        marginLeft:-10,
    },
    bgckImg:{
        width:32,
        height:32,
    },
    bgImage:{
        flex:1,
        paddingHorizontal:33,
    },
    main:{
        flex:1,
    },
    mainContent:{
        flex:1,
        justifyContent:'space-between'
    },
    title:{
        marginTop:120 - 32,
        color:Colors.title,
        fontSize:40,
        fontFamily: 'SmileySans-Oblique',
        marginBottom:95
    },
    inputView:{
        width:'100%',
        height:40,
        borderBottomWidth:1,
        borderBottomColor:Colors.border,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between'
    },
    input:{
        flex:1,
        color:Colors.light,
        fontSize:14,
        paddingVertical:0
    },
    downView:{
        alignItems:'center',
        paddingBottom:10
    },
    loginButton:{
        width:310,
        height:52,
        justifyContent:'center',
        alignItems:'center'
    },
    logintitle:{
        color:Colors.white,
        fontSize:14,
    },
    loginButtonvieew:{
        marginTop:50
    },
    tips:{
        color:Colors.error,
        fontSize:14,
        height:20,
        marginTop:10
    },
    centerView:{
      alignItems:'center'
    },
    codeButton:{
        width:70,
        height:20,
        flexDirection:'row',
        justifyContent:'flex-end'
    },
    codetitle:{
        color:Colors.light,
        fontSize:14,
    },
});
