import { BOTTOM_HEIGHT, SCREEN_HEIGHT, SCREEN_WIDTH, STATUSBAR_SAFE_AREA_HEIGHT } from '@/utils';
import Colors from '@/utils/colors';
import {
    StyleSheet,
} from 'react-native';
export const styles = StyleSheet.create({
    backButton:{
        width:32,
        height:32,
        marginLeft:23,
        marginTop:STATUSBAR_SAFE_AREA_HEIGHT
    },
    bgckImg:{
        width:32,
        height:32,
    },
    bgImage:{
        flex:1,
    },
    topNameView:{
        paddingHorizontal:33,
    },
    main:{
        flex:1,
    },
    mainContent:{
        flex:1,
        justifyContent:'space-between'
    },
    title:{
        marginTop:120 - 32 - STATUSBAR_SAFE_AREA_HEIGHT,
        color:Colors.title,
        fontSize:40,
        fontFamily: 'SmileySans-Oblique',
    },
    tipReg:{
        flexDirection:'row',
        marginTop:5,
        marginBottom:10
    },
    nameView:{
        flexDirection:'row',
        justifyContent:'space-between',
        marginLeft:-63,
        alignItems:'center',
    },
    agreeView:{
        justifyContent:'center',
        width:'100%',
        height:'100%',
        alignItems:'center',
        marginTop:-30,
    },
    agreeText:{
        color:Colors.forbidBg,
        fontSize:12,
    },
    nametitle:{
        fontSize:24,
        color:Colors.bright,
        fontFamily: 'SmileySans-Oblique',
    },
    nameBG:{
        width:'100%',
        height:52,
        justifyContent:'center'
    },
    nameIcon:{
        width:92,
        height:92,
        marginLeft:-60,
        zIndex:2
    },
    nameInput:{
        width:'70%',
        height:'100%',
        fontSize:24,
        color:Colors.white,
        fontFamily: 'SmileySans-Oblique',
        marginLeft:63,
        paddingTop:0,
        paddingBottom:0
    },
    bottombg:{
        width:'100%',
        height:450,
        flex:1,
        alignItems:'center',
        paddingTop:80
    },
    sexImg:{
        width:120,
        height:120
    },
    nextButton:{
        width:310,
        height:52,
        justifyContent:'center',
        alignItems:'center'
    },
    nextButtonView:{
        width:310,
        height:52,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:26,
        marginVertical:50
    },
    nextTitle:{
        color:Colors.bright,
        fontSize:14
    },
    jumpView:{
      position:'absolute',
      bottom:BOTTOM_HEIGHT + 10,
      flexDirection:'row',
      justifyContent:'center',
      width:'100%'
    }
})